version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
configuration: Release
before_build:
   - nuget restore src
build:
  project: src/Alturos.ImageAnnotation.sln
  verbosity: normal